name: CI

on:
  push:
    branches: [ master ]

jobs:
  doc:
    name: Sphinx Pages
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@master

        - name: vuepress-deploy
          uses: jenkey2011/vuepress-deploy@master
          env:
            ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
            BUILD_SCRIPT: yarn && yarn build
            BUILD_DIR: blog/.vuepress/dist/
